### ISSUE TITLE
Custom form in wagtail page ins't accesable in Wagtail admin

### ISSUE THREAD

**Issue by SalahAdDin** [gasman/wagtail-form-example#1]
Hi man,

All is good with this exampl, except by this:
![attributeerror at -admin-forms-submissions-29- - chromium_133](https://cloud.githubusercontent.com/assets/5034215/13037578/30a777ee-d352-11e5-813f-bf7004bda24e.png)
It's comprenssible, yes, because we didn't put a Wagtail Form Fields, custom form instead.

How can we fix it?

**Comment by gasman** [comment]
**Please ask support questions on the mailing list.**
