### ISSUE TITLE
Include example code for having submitted forms become visible in the admin panel

### ISSUE THREAD

**Issue by ironhouzi** [gasman/wagtail-form-example#2]
I am trying to get the best from both worlds: The ability to create complex forms, possibly through using django-crispy-forms, and have the submissions end up in the admin panel's Form section, with added benefits of search and csv export.

**Comment by aresti** [comment]
You're probably better just backing your complex form with a model and adding it to the admin see http://docs.wagtail.io/en/v1.5.2/reference/contrib/modeladmin.html

**Comment by gasman** [comment]
This is out of scope for this project - it's only intended to demonstrate a simple Django-style form.
